
CREATE CONSTRAINT pessoa_id IF NOT EXISTS
FOR (p:Pessoa)
REQUIRE p.id IS UNIQUE;

CREATE CONSTRAINT categoria_id IF NOT EXISTS
FOR (c:Categoria)
REQUIRE c.id IS UNIQUE;

CREATE CONSTRAINT valor_id IF NOT EXISTS
FOR (v:Valor)
REQUIRE v.id IS UNIQUE;

CREATE CONSTRAINT pessoa_nome IF NOT EXISTS
FOR (p:Pessoa)
REQUIRE p.nome IS UNIQUE;

CREATE CONSTRAINT categoria_nome IF NOT EXISTS
FOR (c:Categoria)
REQUIRE c.nome IS UNIQUE;

CREATE CONSTRAINT valor_nome IF NOT EXISTS
FOR (v:Valor)
REQUIRE v.nome IS UNIQUE;
